Add three new graphic classes and some functions for graphic tree comparison
LuCEresearchlab/pytamaro pull request #22
Opened 2023-09-04 07:47 UTC by Niko-creater

1. I add three new graphic classes Above, Beside and Overlay which implemented exactly same as before with skia(path, pin_position) and some simple tests in "test_operation.py"      

2. I expose graphic attributes of all Graphic class for coming graphic tree compison use    

3. the file "graphic_tree_canvas" and the new added attributes "left_node" and "right_node" is just for making printing job of graphic tree easier and graphic tree printing is basically for testing and debugging. All these thing could be deleted at the end.                     

4.the function "get_point_name" (for graphic tree printing)seems stupid and redudent and I try to make it better but I failed. If you know how to make it better please help me with it.

2023-09-05 07:18 UTC, lucach commented
A couple of high-level points that need to be addressed before diving into the details:
- Code that pertains to debugging/visualizing/comparing graphics should not be part of this library but of the separate project that deals with the assessment. 
- The implementation of the `__init__` and `draw` methods in `Above`/`Beside`/`Overlay` should make use of the implementations of those methods in `Compose`/`Pin`. Besides the amount of code duplication, it is quite hard to make sure that all the computations you re-implemented are correct in all edge cases. The methods should essentially mimic what was done before at the function level (i.e., the combination of pin+pin+compose+pin).

2023-09-05 07:19 UTC, lucach commented on pytamaro/color.py
> +        return "rgb:" + str(self.color[0] * 255) + "_" + str(self.color[1] * 255) + "_" + str(self.color[2] * 255) \
BTW: In your separate project, look into f-strings when you need to do this kind of string interpolation.

2023-09-05 11:54 UTC, Niko-creater commented
Hi Luca I have modified my codes according to your feedback, please check them again. Thanks a lot!

2023-09-05 14:18 UTC, lucach requested changes

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        # For graphic tree comparison
Mmh. Given that these attributes are useful in general, I would simply store them at the beginning of the `__init__` method, without any specific comment ("for graphic tree comparison").

It might be possible to turn all of them into dataclasses (so that we don't need to manually perform all these assignments), but then you would probably need to fight with [Post init processing](https://docs.python.org/3/library/dataclasses.html#post-init-processing).

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        # For graphic tree comparison
Same as above (here you can see why doing things manually is a bad idea: why is the color not stored here?)

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        # For graphic tree comparison
Same as above (and in all the classes below, I won't comment further).

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +
Why are there all these extra newlines? Have you checked whether the code conforms to the style checks (e.g., by running `pylint`)?

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        self.degree = - deg
No space after unary minus (this would go away if we use a dataclass -- but then you need to update any client code).
I'd store the parameter unmodified.

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +    Represent the composition of two graphics that beside with each other,
Represent**s** the composition of two graphics one beside the other,
vertically centered.

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        b_g = Pin(Compose(Pin(left_graphic, center_right), Pin(right_graphic, center_left)), center)
Can we use a more descriptive name? I assume `g` stands for graphic, `b`?

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        b_g = Pin(Compose(Pin(self.left_graphic, center_right), Pin(self.right_graphic, center_left)), center)
Oh no, let's not compute this twice (and also duplicate code)!
It can be stored as an attribute.

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +    Represent the composition of two graphics that one above other,
Represents the composition of two graphics one above the other,
horizontally centered.

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        a_b = Pin(Compose(Pin(self.top_graphic, bottom_center), Pin(self.bottom_graphic, top_center)), center)
Same as above. Oh, now I get it: this is short for "above graphic". What about `composed_graphic`?

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        o_g = Pin(Compose(Pin(self.front_graphic, center), Pin(self.back_graphic, center)), center)
Same.

2023-09-05 14:18 UTC, lucach commented on tests/test_graphic.py
> +from pytamaro.primitives import empty_graphic, rectangle, ellipse
Why is this added?

2023-09-05 14:18 UTC, lucach commented on pytamaro/operations.py
> +    return Overlay(foreground_graphic, background_graphic)
I guess this means that the `_compose_pin_center` function is no longer needed.

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        self.angle = angle
Missing color?

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        self.text_size = size
Missing color?

2023-09-05 14:18 UTC, lucach commented on pytamaro/graphic.py
> +        o_g = Pin(Compose(Pin(front_graphic, center), Pin(back_graphic, center)), center)
If I'm not missing something, I think one should be able to factor out this common logic among the three classes (e.g., in an intermediate class in the hierarchy named something like `SimpleCompose` which extends `Graphic` and from which `Above` `Beside` and `Overlay` are further derived).
They could share the same `draw` method, which would make use of the shared `composed_graphic` attribute.

2023-09-06 08:56 UTC, Niko-creater commented
Hi Luca, I have corrected all the inappropriate code based on your comments and I feel sorry for bringing you such bad code. Thank you so much for providing me detailed feedback and I really enjoy learning from them. If there still exists any code need to be improved, please let me know :D

2023-09-06 13:29 UTC, lucach commented
Hi! No need to apologize or feel bad! :-)
We all write code that can be improved, and this is indeed an opportunity to learn!

The changes are now closer to how I imagined them. I still have a couple of doubts:
- Is there a reason behind turning only `SimpleCompose` into a dataclass (and not all the other classes, which would have spared all the assignments to store the parameters)?
- `SimpleCompose` could take care of doing the composition with the extra pin on the center (exactly like `_compose_pin_center` was abstracting the behavior of the three specialized versions), and `Above`/`Beside`/`Overlay` could just pass the relevant parameters (the graphics and the points).

2023-09-07 09:20 UTC, Niko-creater commented
Hi Luca, I follow your second suggestion and now SimpleCompose functions like previous `_compose_pin_center`.
As for your first suggestion, I try to rewrite `Above`\`Overlay`\`Beside` three classes as dataclass, but because of the inheritance of dataclass, when we need to create a new object of one class, we have to assign all the fields of this class and its inherited classes.(for instance after I turn Beside into dataclass, the Beside.__init__() will required positional arguments: 'pin_position', 'path'(from inherited dataclass `Graphic`), 'graphic1', 'graphic2', 'point1', 'point2'(from inherited dataclass `SimpleCompose`), 'left_graphic', and 'right_graphic'). And I try to use post-init processing and init-only variables to fix this but I fail. 
I dont know if I miss something and if you have any thoughts to solve this please share with me:D

2023-09-08 12:16 UTC, lucach commented
It's not your fault! Unfortunately, this whole `dataclass` approach is still rather messy for non-trivial use cases like ours. I tried to come up with a solution in https://github.com/LuCEresearchlab/pytamaro/pull/22/commits/f154990d57b0d75acc25b3a15717d1088598f7df. As you can see, it's quite a lot of changes.

The commit message explains in some detail the compromise I reached. It's probably not as clean as it could be, but it should fulfill all our requirements. Eventually, I decided to manually implement the constructors so that we could compute the required fields for the superclass(es). Among the other benefits, PyTamaro `Graphic`s now have slightly more informative string representations and ""emulate immutability"".

This should be ready to be merged, but before doing that I'd like you to try to update your graphics-comparison code, to see whether these new changes address 100% of the aspects that were missing before.

2023-09-10 14:16 UTC, Niko-creater commented
Hi Luca. Thanks for detailed commit messages and they are very helpful! Currently I'm still struggling with the implemetion of my new graphic tree comparison and feedback algorithm, but I can confirm that the current version pytamaro has fulfil my need. So I think the code could be merged.

2023-11-03 10:14 UTC, lucach commented
No news is good news... I am therefore merging this so that I can make other changes to the library that depend on this.

2023-11-03 10:15 UTC, merged

2023-11-03 14:25 UTC, Niko-creater commented
Glad to hear that:3